travis:
  secure:
    BINSTAR_TOKEN: nSL6sewDC0Hn7Wv4Cz1i++9n3hRHiOy1qR2ZDA3s6m9TQ+0NQUxS7iC4ZowXQ2uIjFyMxPuY5owbPihvN5gPSu6qezN8jd04mBmYg+EoA1enILXakp7ERYJPz/ttBPszEs8wWxe9ffbb7v43viKPqObMocqoyJZghwdYYfmuvepjErf5UoNsmEFjl7u7JnMtBxCl/8F6DvHHsXThcIWP9130uFU+Us0RTQBHLQC6t47cZGD3WBppMZJ4rcyKQwF/Z0/ob7sgNZC57yq/oQ/o4Bs0hqpGMQ5km9EX4o88zma93ibomX0IFzk2HFYh4MiKboggZnyRfevn987OI2UyfFEZrgtA/SpJE7Nqtyn+lmN4LW38rGoEwVP6IA+wUOwzc/Id28Ne7D3VM8rdOBzg4J0VZ/0H9jvJbVaDdjULExIi9iC+AgpWac8tfldldFmnyDVCCNc7s3HPRUMhF/+MJby0E8W4Tw3i7t+l8okurRYXV2uyI30XuIdGVXlWM7E9jufinYoEU93M/F3j+iKA1u4ORwsJZ3S04nTUkFO9iVlVdfv7UmUzoO6PlM9PoiUVTcJmXkBXHrtktYCLA7R9hQ4TDy0mxmlboMWndAb4WaPdqkLeYuer/VWJWcQTU20cXJiH5bk9RrgbuXVMrYL2RolTfHBdiE8p8E9JK8Tjp1I=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
