travis:
  secure:
    BINSTAR_TOKEN: jIpIhgvbtOfBkKisEojSwmvfyTuTlFaEBodvA+PguWCPBNtmxYbcMaC+xtDfocRWYQO3Fhfp0kAFuPU/MOveCF9u7DKYj2e4Xn3OPiSheSxHl6XWYntp2c/cu0L7XhZvfM9FdBTQR4ifRKgg/A2tciKcn0FW6DUfBhPobeLu4Z/CmzcUVwYE6iocF5A8U/+aSYWiqgOFI2SUSTpdJD/5pfnNS7I9QXYCWIP4Ud+iF+DHvt6u7d3qJW38BajE49Kr2VH0oHzbhkIV76wgcbSj858DMtaT1a3rifyyXyFTIlK9fPrbljRBpFVLkX5chigCAjhOWtlmWUUDJV8k79rqTEZs+SOgH4+Vn6YlZ5OCTySlGNoDrO758qUMXrPL96YIFk73kgRZ8Q34vyU0H6q4NU5qJtmsjValWy2Kte6YTeltfwxu0+r3vtYM6SMnogwlwndrEeBU9hWuuu65MMSNWtQXsUHYEk17GFsRx8/Q8nLn9U/kHIsw20Vd1Gs7m27MSA+0YM0ZNyZyPwfRKtOaP6ArT1oIuwGbDlwLdjoVyM0JAlgifQyYyygOBsOK0WiVjpcij4DxOXCqcwv0O6yuhZXvXV/uDZIxlLU3EMhjqrzzJ5PA9gO5BAEJPXuXuQQoyMsd5p6V7hNyr0VYmMfTXRf6kuNK/TbrImkeJtc6m0Q=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
